"""
Persistent-Code MCP Server

A Model Context Protocol server that creates and maintains a knowledge graph
of code generated by Claude to maintain context across sessions.
"""

from .knowledge_graph import KnowledgeGraph, ComponentType, ComponentStatus, RelationshipType
from .code_analyzer import CodeAnalyzer
from .context_assembler import ContextAssembler
from .config import Config, config
from .llama_index_manager import LlamaIndexManager

__version__ = "0.2.0"
